"""empty message

Revision ID: 0cea980b74c1
Revises: 907ad8e1f6b0
Create Date: 2021-01-21 03:30:28.059680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cea980b74c1'
down_revision = '907ad8e1f6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_venue')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('artist', 'seeking_talent')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
